profiles/profiles.json

Thanks for the opportunity to contribute

Added my profile

---

profiles/profiles.json

Thank you so much for the opportunity to learn and contribute

Added Kunal Kushwaha Profile

---

profiles/profiles.json

Add my profile - Krish Jaiswal

---

profiles/profiles.json

I have updated profile.json with required details.

profile.json updated by harsh1x4

---

profiles/profiles.json

It would be helpful for people to checkout and learn about Web3

Added Learn Web3 profile

---

profiles/profiles.json

Just added some lines in profiles.json

Added my profile 😇

---

scripts/app.js
styles/index.css

https://user-images.githubusercontent.com/80192140/193409727-17a7b4b9-e219-451b-86b1-cf8334c4f182.mp4

feat: Update Profile Card UI

---

index.html
profiles/profiles.json
scripts/app.js
styles/index.css

https://user-images.githubusercontent.com/80192140/193486347-32e92b3c-911c-4a42-89a3-d00734357e2f.mp4

Add follow button and fix broken Image

---

profiles/profiles.json

Updated: Added my profile on `profiles.json`

---

profiles/profiles.json

Update: Changed the profile picture in `profiles.json`

---

profiles/profiles.json

Broken profile picture of Kunal Kushwaha has been fixed.

profile picture fixed

---

profiles/profiles.json

Update profiles.json - Profile add request

---

profiles/profiles.json

Hello 👋
I have added my image, username, and name to the project to the project. 
Kindly update it!!!

Please add my profile

---

profiles/profiles.json

Added my info under profile section.

Added my name to profiles.json

---

profiles/profiles.json

Profile Added

---

profiles/profiles.json

I have added my profile on TechCreators.
Please merge my PR..

added myprofile

---

profiles/profiles.json

added shubham verma twitter link

---

index.html
profiles/profiles.json
scripts/app.js
styles/index.css

- reformatted code
- Added "No profile to show" message (Check issue #65)
- Added image alts

Solves #65

---

profiles/profiles.json

adding my profile

---

styles/index.css

After reporting the overflow for the mobile site preview (#67), I've fixed the issue, and made the nav-bar responsive.

fix: body overflow fixed (#67)

---

index.html
scripts/app.js
styles/index.css

As the icon of a sun and moon i used a nice and very handy icon library which is called "Font Awesome". I hope you liked my work. If there will be any problems or something you want to change just write to me i will chagne it immediately 😄

Added dark mode to the website

---

profiles/profiles.json

- Fix: syntax error in `profiles.json` file.
- Now all profiles are loading properly on website.

Bug Fix: Profile not showing on website

---

profiles/profiles.json

- Added my profile image URL, twitter username and full name. 
Thank you.

New Profile: added my profile data 

---

styles/index.css

Here I Updated ScrollBar Color to #A0A0A0 color

Scroll Bar Added

---

styles/index.css

**Just Modify Background In Night Mode **

Background-Updation:

---

profiles/profiles.json

My Twitter Profile was added (@kathira28925922)

My Twitter Profile was added (@kathira28925922)

---

.github/pull_request_template.md

feat : Add Pull Request Template

---

profiles/profiles.json

Adding Ali Calimli Profile

---

styles/index.css

Please delete options that are not relevant.
a. Give a descriptive title to your PR.
b. Describe your changes.
c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

Modified Github Icon on DarkMode

---

profiles/profiles.json

With this PR, I added the profile of Danny Thompson, a popular and influential Twitter Tech Creator

add danny thompson profile

---

profiles/profiles.json

Added my profile of ddmasterdon

Added to profiles.json
